/*
 * fast-completer - Universal fast completion provider for CLI tools
 *
 * Usage: fast-completer [options] <format> <spans...>
 *
 * This program reads completion data from a binary blob file generated by
 * generate_blob.c, allowing a single completer binary to work with any CLI.
 *
 * The CLI name is derived from the first span and used to look up
 * <name>.fcmpb in the cache directory. Use --blob to specify an explicit path.
 *
 * The last span triggers completions:
 *   "" - subcommands + flags
 *   "-" or "--*" - flags only
 *   "abc..." - matching subcommands
 *
 * Output formats:
 *   lines, zsh, tsv, json, pwsh
 *   Aliases: bash -> lines, fish -> tsv
 */

#include <errno.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <ctype.h>

#include "generate_blob.h"

#ifdef _WIN32
#define WIN32_LEAN_AND_MEAN
#include <windows.h>
#include <io.h>
#include "compat/getopt.h"
#else
#include <fcntl.h>
#include <getopt.h>
#include <poll.h>
#include <signal.h>
#include <spawn.h>
#include <sys/mman.h>
#include <sys/stat.h>
#include <sys/wait.h>
#include <time.h>
#include <unistd.h>
#endif

// Supported output formats
typedef enum {
    OUT_LINES,
    OUT_ZSH,
    OUT_TSV,
    OUT_JSON,
    OUT_PWSH,
    OUT_UNKNOWN
} OutputFormat;

// Completion types (for PowerShell)
typedef enum {
    COMP_COMMAND = 2,
    COMP_PARAM_NAME = 7,
    COMP_PARAM_VALUE = 8
} CompletionType;

// String with known length
typedef struct { const char *p; size_t n; } String;

// Create String from string literal
#define STR_LIT(s) ((String){s, sizeof(s) - 1})

// Compare String against string literal (length check + memcmp)
#define STR_EQ_LIT(s, lit) ((s).n == sizeof(lit) - 1 && memcmp((s).p, lit, sizeof(lit) - 1) == 0)

static inline String str_get(uint32_t off);
static void output_completion(String value, String desc, CompletionType type);
static void output_completion_prefixed(const char *prefix, size_t prefix_len,
                                       String value, String desc, CompletionType type);

// Structs matching binary format (4-byte aligned)
typedef struct {
    uint32_t name_off;
    uint32_t short_off;    // 0 if none, else offset into string table
    uint32_t desc_off;
    uint32_t choices_off;  // 0 if none, else absolute offset into blob
    uint8_t  flags;        // FLAG_TAKES_VALUE, FLAG_IS_MEMBERS
    uint8_t  _pad[3];
} Param;

typedef struct {
    uint32_t name_off;
    uint32_t desc_off;
    uint32_t params_idx;
    uint16_t subcommands_idx;
    uint16_t params_count;
    uint16_t subcommands_count;
    uint16_t _pad;
} Command;

typedef char _assert_param_size[(sizeof(Param) == PARAM_SIZE) ? 1 : -1];
typedef char _assert_command_size[(sizeof(Command) == COMMAND_SIZE) ? 1 : -1];

// Blob header (parsed at load time - only fields actually used)
typedef struct {
    uint32_t max_command_path_len;
    uint32_t string_table_off;
    uint32_t commands_off;
    uint32_t params_off;
    uint32_t root_command_off;
} BlobHeader;

// Global state
static const uint8_t *blob = NULL;
static BlobHeader header;
static OutputFormat output_format;
static bool has_descriptions = true;  // Set from blob flags
static bool add_trailing_space = false;  // Add trailing space to completion values
static bool full_commands = false;       // Complete full leaf command paths instead of next level
static bool quiet_mode = false;          // Suppress "blob not found" error (for fallback scripts)

// Working buffers (allocated based on header values)
static char *path_buf = NULL;

// Completion context (set once per complete() call)
static const char **g_spans = NULL;
static size_t *g_arg_lens = NULL;
static int g_span_count = 0;

// Hash set for O(1) used-param lookups (lazily built only when completing params)
// For small span counts, linear scan is faster (avoids 4KB memset overhead)
#define USED_LINEAR_THRESHOLD 8
#define USED_SET_SIZE 256  // Power of 2, must be > 2*MAX_SPANS
typedef struct { const char *p; size_t n; } UsedEntry;
static UsedEntry g_used_set[USED_SET_SIZE];
static bool g_used_set_ready = false;
static bool g_used_short[256];
static bool g_used_short_ready = false;

// Emitted option de-duplication (across inheritance)
#define EMIT_SET_SIZE 512
static UsedEntry g_emit_set[EMIT_SET_SIZE];
static bool g_emit_set_ready = false;

// Cache for dynamic completer results (per invocation)
typedef struct {
    char *s;
    size_t n;
} CacheValue;

typedef struct {
    uint32_t hash;
    uint32_t index;
} CacheSetEntry;

typedef struct {
    char *cli;
    size_t cli_len;
    char *completer;
    size_t completer_len;
    char *prefix;
    size_t prefix_len;
    CacheValue *values;
    size_t count;
    size_t cap;
    CacheSetEntry *dedupe;
    size_t dedupe_count;
    size_t dedupe_cap;
} CompleterCacheEntry;

static bool completer_cache_dedupe_contains(CompleterCacheEntry *e, const char *s, size_t n, uint32_t h);
static bool completer_cache_dedupe_insert(CompleterCacheEntry *e, uint32_t h, uint32_t index);

static CompleterCacheEntry *g_completer_cache = NULL;
static size_t g_completer_cache_count = 0;
static size_t g_completer_cache_cap = 0;

static int g_completer_timeout_ms = 1000;
static bool g_completer_timeout_override = false;

static inline uint32_t hash_str(const char *p, size_t n) {
    uint32_t h = 5381;
    for (size_t i = 0; i < n; i++) h = ((h << 5) + h) ^ (uint8_t)p[i];
    return h;
}

static inline uint32_t hash_str_nonzero(const char *p, size_t n) {
    uint32_t h = hash_str(p, n);
    return h ? h : 1;
}

static size_t next_pow2(size_t n) {
    size_t p = 1;
    while (p < n) p <<= 1;
    return p;
}

static char *dup_span(const char *p, size_t n) {
    char *s = malloc(n + 1);
    if (!s) return NULL;
    memcpy(s, p, n);
    s[n] = '\0';
    return s;
}

static void completer_cache_clear(void) {
    for (size_t i = 0; i < g_completer_cache_count; i++) {
        CompleterCacheEntry *e = &g_completer_cache[i];
        free(e->cli);
        free(e->completer);
        free(e->prefix);
        for (size_t j = 0; j < e->count; j++) {
            free(e->values[j].s);
        }
        free(e->values);
        free(e->dedupe);
    }
    free(g_completer_cache);
    g_completer_cache = NULL;
    g_completer_cache_count = 0;
    g_completer_cache_cap = 0;
}

static CompleterCacheEntry *completer_cache_find(const char *cli, String completer,
                                                 const char *prefix, size_t prefix_len) {
    size_t cli_len = strlen(cli);
    const char *pfx = prefix ? prefix : "";
    for (size_t i = 0; i < g_completer_cache_count; i++) {
        CompleterCacheEntry *e = &g_completer_cache[i];
        if (e->cli_len != cli_len || e->completer_len != completer.n || e->prefix_len != prefix_len)
            continue;
        if (memcmp(e->cli, cli, cli_len) != 0) continue;
        if (memcmp(e->completer, completer.p, completer.n) != 0) continue;
        if (prefix_len && memcmp(e->prefix, pfx, prefix_len) != 0) continue;
        if (prefix_len == 0 && e->prefix_len == 0) return e;
        if (prefix_len == e->prefix_len) return e;
    }
    return NULL;
}

static CompleterCacheEntry *completer_cache_add(const char *cli, String completer,
                                                const char *prefix, size_t prefix_len) {
    if (g_completer_cache_count >= g_completer_cache_cap) {
        size_t next = g_completer_cache_cap ? g_completer_cache_cap * 2 : 8;
        CompleterCacheEntry *tmp = realloc(g_completer_cache, next * sizeof(CompleterCacheEntry));
        if (!tmp) return NULL;
        g_completer_cache = tmp;
        g_completer_cache_cap = next;
    }
    CompleterCacheEntry *e = &g_completer_cache[g_completer_cache_count];
    memset(e, 0, sizeof(*e));
    e->cli_len = strlen(cli);
    e->completer_len = completer.n;
    e->prefix_len = prefix_len;
    e->cli = dup_span(cli, e->cli_len);
    e->completer = dup_span(completer.p, completer.n);
    e->prefix = dup_span(prefix ? prefix : "", prefix_len);
    if (!e->cli || !e->completer || !e->prefix) {
        free(e->cli);
        free(e->completer);
        free(e->prefix);
        e->cli = e->completer = e->prefix = NULL;
        return NULL;
    }
    g_completer_cache_count++;
    return e;
}

static void completer_cache_add_value(CompleterCacheEntry *e, const char *s, size_t n) {
    if (!e || n == 0) return;
    uint32_t h = hash_str_nonzero(s, n);
    if (completer_cache_dedupe_contains(e, s, n, h)) return;
    if (e->count >= e->cap) {
        size_t next = e->cap ? e->cap * 2 : 8;
        CacheValue *tmp = realloc(e->values, next * sizeof(CacheValue));
        if (!tmp) return;
        e->values = tmp;
        e->cap = next;
    }
    char *copy = dup_span(s, n);
    if (!copy) return;
    if (!completer_cache_dedupe_insert(e, h, (uint32_t)e->count)) {
        free(copy);
        return;
    }
    e->values[e->count].s = copy;
    e->values[e->count].n = n;
    e->count++;
}

static void completer_cache_emit(const CompleterCacheEntry *e, String out_prefix) {
    if (!e) return;
    for (size_t i = 0; i < e->count; i++) {
        String v = {e->values[i].s, e->values[i].n};
        if (out_prefix.p && out_prefix.n > 0) {
            output_completion_prefixed(out_prefix.p, out_prefix.n, v, str_get(0), COMP_PARAM_VALUE);
        } else {
            output_completion(v, str_get(0), COMP_PARAM_VALUE);
        }
    }
}

static void completer_cache_free_values(CompleterCacheEntry *e) {
    if (!e) return;
    for (size_t i = 0; i < e->count; i++) free(e->values[i].s);
    free(e->values);
    e->values = NULL;
    e->count = 0;
    e->cap = 0;
    free(e->dedupe);
    e->dedupe = NULL;
    e->dedupe_count = 0;
    e->dedupe_cap = 0;
}

static void completer_cache_remove(CompleterCacheEntry *e) {
    if (!e) return;
    size_t idx = (size_t)-1;
    for (size_t i = 0; i < g_completer_cache_count; i++) {
        if (&g_completer_cache[i] == e) { idx = i; break; }
    }
    if (idx == (size_t)-1) return;
    completer_cache_free_values(e);
    free(e->cli);
    free(e->completer);
    free(e->prefix);
    if (idx + 1 < g_completer_cache_count) {
        g_completer_cache[idx] = g_completer_cache[g_completer_cache_count - 1];
    }
    g_completer_cache_count--;
}

static bool completer_cache_dedupe_rehash(CompleterCacheEntry *e, size_t new_cap) {
    new_cap = next_pow2(new_cap);
    CacheSetEntry *table = calloc(new_cap, sizeof(CacheSetEntry));
    if (!table) return false;
    for (size_t i = 0; i < e->count; i++) {
        CacheValue *v = &e->values[i];
        uint32_t h = hash_str_nonzero(v->s, v->n);
        size_t mask = new_cap - 1;
        size_t idx = h & mask;
        while (table[idx].hash) idx = (idx + 1) & mask;
        table[idx].hash = h;
        table[idx].index = (uint32_t)i;
    }
    free(e->dedupe);
    e->dedupe = table;
    e->dedupe_cap = new_cap;
    e->dedupe_count = e->count;
    return true;
}

static bool completer_cache_dedupe_contains(CompleterCacheEntry *e, const char *s, size_t n, uint32_t h) {
    if (!e->dedupe || e->dedupe_cap == 0) return false;
    size_t mask = e->dedupe_cap - 1;
    size_t idx = h & mask;
    while (e->dedupe[idx].hash) {
        if (e->dedupe[idx].hash == h) {
            CacheValue *v = &e->values[e->dedupe[idx].index];
            if (v->n == n && memcmp(v->s, s, n) == 0) return true;
        }
        idx = (idx + 1) & mask;
    }
    return false;
}

static bool completer_cache_dedupe_insert(CompleterCacheEntry *e, uint32_t h, uint32_t index) {
    if (!e->dedupe || e->dedupe_cap == 0) {
        if (!completer_cache_dedupe_rehash(e, 32)) return false;
    }
    if (e->dedupe_count * 10 >= e->dedupe_cap * 7) {
        if (!completer_cache_dedupe_rehash(e, e->dedupe_cap * 2)) return false;
    }
    size_t mask = e->dedupe_cap - 1;
    size_t idx = h & mask;
    while (e->dedupe[idx].hash) idx = (idx + 1) & mask;
    e->dedupe[idx].hash = h;
    e->dedupe[idx].index = index;
    e->dedupe_count++;
    return true;
}

static inline void used_set_add(const char *p, size_t n) {
    size_t idx = hash_str(p, n) & (USED_SET_SIZE - 1);
    while (g_used_set[idx].p) {
        idx = (idx + 1) & (USED_SET_SIZE - 1);
    }
    g_used_set[idx].p = p;
    g_used_set[idx].n = n;
}

static inline bool is_short_cluster_token(const char *p, size_t n) {
    if (n <= 2 || n > 4) return false;  // Heuristic: only small clusters like -abc
    for (size_t i = 1; i < n; i++) {
        if (!((p[i] >= 'a' && p[i] <= 'z') || (p[i] >= 'A' && p[i] <= 'Z'))) return false;
    }
    return true;
}

static inline void used_short_mark(const char *p, size_t n) {
    if (n < 2 || p[0] != '-' || p[1] == '-') return;
    g_used_short[(unsigned char)p[1]] = true;
    if (is_short_cluster_token(p, n)) {
        for (size_t i = 2; i < n; i++) g_used_short[(unsigned char)p[i]] = true;
    }
}

static inline void emit_set_reset(void) {
    memset(g_emit_set, 0, sizeof(g_emit_set));
    g_emit_set_ready = true;
}

static inline bool emit_set_contains(const char *p, size_t n) {
    size_t idx = hash_str(p, n) & (EMIT_SET_SIZE - 1);
    while (g_emit_set[idx].p) {
        if (g_emit_set[idx].n == n && memcmp(g_emit_set[idx].p, p, n) == 0) return true;
        idx = (idx + 1) & (EMIT_SET_SIZE - 1);
    }
    return false;
}

static inline void emit_set_add(const char *p, size_t n) {
    size_t idx = hash_str(p, n) & (EMIT_SET_SIZE - 1);
    while (g_emit_set[idx].p) {
        if (g_emit_set[idx].n == n && memcmp(g_emit_set[idx].p, p, n) == 0) return;
        idx = (idx + 1) & (EMIT_SET_SIZE - 1);
    }
    g_emit_set[idx].p = p;
    g_emit_set[idx].n = n;
}

static void used_set_build(void) {
    if (g_used_set_ready && g_used_short_ready) return;
    memset(g_used_set, 0, sizeof(g_used_set));
    memset(g_used_short, 0, sizeof(g_used_short));
    for (int i = 0; i < g_span_count; i++) {
        const char *span = g_spans[i];
        if (span[0] != '-') continue;
        size_t n = g_arg_lens[i];
        if (n >= 2 && span[1] == '-') {
            const char *eq = memchr(span, '=', n);
            size_t base_len = eq ? (size_t)(eq - span) : n;
            if (base_len > 1) used_set_add(span, base_len);
        } else {
            used_short_mark(span, n);
        }
    }
    g_used_set_ready = true;
    g_used_short_ready = true;
}

static bool used_set_contains(const char *p, size_t n) {
    size_t idx = hash_str(p, n) & (USED_SET_SIZE - 1);
    while (g_used_set[idx].p) {
        if (g_used_set[idx].n == n && memcmp(g_used_set[idx].p, p, n) == 0) return true;
        idx = (idx + 1) & (USED_SET_SIZE - 1);
    }
    return false;
}

// Accessor macros
#define PARAM_TAKES_VALUE(p)   ((p)->flags & FLAG_TAKES_VALUE)
#define PARAM_IS_MEMBERS(p)    ((p)->flags & FLAG_IS_MEMBERS)
#define PARAM_IS_COMPLETER(p)  ((p)->flags & FLAG_IS_COMPLETER)
#define PARAM_HAS_CHOICES(p)   ((p)->choices_off && !((p)->flags & (FLAG_IS_MEMBERS | FLAG_IS_COMPLETER)))
#define PARAM_HAS_MEMBERS(p)   ((p)->choices_off && ((p)->flags & FLAG_IS_MEMBERS))
#define PARAM_HAS_COMPLETER(p) ((p)->choices_off && ((p)->flags & FLAG_IS_COMPLETER))

// Get string from string table
static inline String str_get(uint32_t off) {
    String s;
    if (off == 0) {
        s.p = "";
        s.n = 0;
        return s;
    }
    const uint8_t *p = blob + header.string_table_off + off;
    if (p[0] < 128) {
        s.n = p[0];
        s.p = (const char *)(p + 1);
    } else {
        s.n = ((p[0] & 0x7f) << 8) | p[1];
        s.p = (const char *)(p + 2);
    }
    return s;
}

// Get command by index
static inline const Command *get_command(uint32_t idx) {
    return (const Command *)(blob + header.commands_off + idx * COMMAND_SIZE);
}

// Get param by index
static inline const Param *get_param(uint32_t idx) {
    return (const Param *)(blob + header.params_off + idx * PARAM_SIZE);
}

// Get root command
static inline const Command *get_root_command(void) {
    return (const Command *)(blob + header.root_command_off);
}

// Get command's params (NULL if none)
static inline const Param *cmd_params(const Command *cmd) {
    return cmd->params_count ? get_param(cmd->params_idx) : NULL;
}

// Get command's subcommands (NULL if none)
static inline const Command *cmd_subcommands(const Command *cmd) {
    return cmd->subcommands_count ? get_command(cmd->subcommands_idx) : NULL;
}

// Read count-prefixed array of string offsets
// Format: u8 count if <255, else 0xFF + u16 count, padded to 4 bytes,
// then count * u32 offsets
static inline uint16_t get_string_list_count(uint32_t off) {
    uint8_t first = blob[off];
    if (first < 255) return first;
    uint16_t val;
    memcpy(&val, blob + off + 1, sizeof(val));
    return val;
}

static inline const uint32_t *get_string_offsets(uint32_t off) {
    return (const uint32_t *)(blob + off + 4);
}

// Track if we've started the JSON array
static bool json_started = false;

static inline bool needs_trailing_space(String s) {
    return s.n > 0 && s.p[s.n - 1] != '=';
}

static inline bool needs_trailing_space_concat(const char *prefix, size_t prefix_len, String s) {
    if (s.n > 0) return s.p[s.n - 1] != '=';
    return prefix_len > 0 && prefix[prefix_len - 1] != '=';
}

static inline bool stdout_is_tty(void) {
#ifdef _WIN32
    return _isatty(_fileno(stdout));
#else
    return isatty(fileno(stdout));
#endif
}

static void init_completer_timeout(void) {
    if (g_completer_timeout_override) return;
    const char *env = getenv("FAST_COMPLETER_TIMEOUT_MS");
    if (!env || !*env) return;
    char *endptr = NULL;
    long val = strtol(env, &endptr, 10);
    if (!endptr || *endptr != '\0' || val <= 0) return;
    if (val > INT32_MAX) val = INT32_MAX;
    g_completer_timeout_ms = (int)val;
}

// I/O helpers
#if defined(_MSC_VER)
// MSVC: use _nolock variants
static inline void put_char(int c) {
    _putc_nolock(c, stdout);
}
static inline void put_bytes(const char *p, size_t n) {
    _fwrite_nolock(p, 1, n, stdout);
}
#define flockfile(f) _lock_file(f)
#define funlockfile(f) _unlock_file(f)
#elif defined(_WIN32)
// MinGW: use standard functions (no unlocked variants)
static inline void put_char(int c) {
    putc(c, stdout);
}
static inline void put_bytes(const char *p, size_t n) {
    fwrite(p, 1, n, stdout);
}
#define flockfile(f) (void)(f)
#define funlockfile(f) (void)(f)
#elif defined(__APPLE__)
// macOS: no fwrite_unlocked
static inline void put_char(int c) {
    putc_unlocked(c, stdout);
}
#define put_bytes(p, n) fwrite(p, 1, n, stdout)
#else
// Linux/other Unix: use unlocked variants
static inline void put_char(int c) {
    putc_unlocked(c, stdout);
}
static inline void put_bytes(const char *p, size_t n) {
    fwrite_unlocked(p, 1, n, stdout);
}
#endif

#define put_lit(s) put_bytes(s, sizeof(s) - 1)

static inline void put_str(String s) {
    put_bytes(s.p, s.n);
}

// JSON string escaping
static void print_json_str_inner(String s) {
    static const char hex[] = "0123456789abcdef";
    for (size_t i = 0; i < s.n; i++) {
        switch (s.p[i]) {
            case '"':  put_lit("\\\""); break;
            case '\\': put_lit("\\\\"); break;
            case '\n': put_lit("\\n"); break;
            case '\r': put_lit("\\r"); break;
            case '\t': put_lit("\\t"); break;
            default:
                if ((unsigned char)s.p[i] < 32) {
                    put_lit("\\u00");
                    put_char(hex[(unsigned char)s.p[i] >> 4]);
                    put_char(hex[(unsigned char)s.p[i] & 0xf]);
                } else {
                    put_char(s.p[i]);
                }
        }
    }
}

static void print_json_str(String s) {
    put_char('"');
    print_json_str_inner(s);
    put_char('"');
}

static void print_json_str_with_space(String s) {
    put_char('"');
    print_json_str_inner(s);
    put_char(' ');
    put_char('"');
}

// Output a completion item
static void output_completion(String value, String desc, CompletionType type) {
    switch (output_format) {
        case OUT_JSON:
            if (json_started) put_char(',');
            json_started = true;
            put_char('{');
            print_json_str(STR_LIT("value"));
            put_char(':');
            if (add_trailing_space && needs_trailing_space(value))
                print_json_str_with_space(value);
            else
                print_json_str(value);
            if (desc.n > 0) {
                put_char(',');
                print_json_str(STR_LIT("description"));
                put_char(':');
                print_json_str(desc);
            }
            put_char('}');
            break;

        case OUT_TSV:
            put_str(value);
            if (add_trailing_space && needs_trailing_space(value))
                put_char(' ');
            if (desc.n > 0) {
                put_char('\t');
                put_str(desc);
            }
            put_char('\n');
            break;

        case OUT_ZSH:
            put_str(value);
            if (add_trailing_space && needs_trailing_space(value))
                put_char(' ');
            if (desc.n > 0) {
                put_char(':');
                for (size_t i = 0; i < desc.n; i++) {
                    if (desc.p[i] == '\\') put_char('\\');  // escape backslashes
                    put_char(desc.p[i]);
                }
            }
            put_char('\n');
            break;

        case OUT_LINES:
            put_str(value);
            if (add_trailing_space && needs_trailing_space(value))
                put_char(' ');
            put_char('\n');
            break;

        case OUT_PWSH:
            put_str(value);
            if (add_trailing_space && needs_trailing_space(value))
                put_char(' ');
            put_char('\t');
            put_str(value);
            put_char('\t');
            put_char('0' + type);
            put_char('\t');
            put_str(desc.n > 0 ? desc : value);
            put_char('\n');
            break;

        case OUT_UNKNOWN:
            break;  // Should never happen
    }
}

static void output_completion_prefixed(const char *prefix, size_t prefix_len,
                                       String value, String desc, CompletionType type) {
    if (!prefix || prefix_len == 0) {
        output_completion(value, desc, type);
        return;
    }
    bool add_space = add_trailing_space && needs_trailing_space_concat(prefix, prefix_len, value);
    switch (output_format) {
        case OUT_JSON:
            if (json_started) put_char(',');
            json_started = true;
            put_char('{');
            print_json_str(STR_LIT("value"));
            put_char(':');
            put_char('"');
            print_json_str_inner((String){prefix, prefix_len});
            print_json_str_inner(value);
            if (add_space) put_char(' ');
            put_char('"');
            if (desc.n > 0) {
                put_char(',');
                print_json_str(STR_LIT("description"));
                put_char(':');
                print_json_str(desc);
            }
            put_char('}');
            break;

        case OUT_TSV:
            put_bytes(prefix, prefix_len);
            put_str(value);
            if (add_space) put_char(' ');
            if (desc.n > 0) {
                put_char('\t');
                put_str(desc);
            }
            put_char('\n');
            break;

        case OUT_ZSH:
            put_bytes(prefix, prefix_len);
            put_str(value);
            if (add_space) put_char(' ');
            if (desc.n > 0) {
                put_char(':');
                for (size_t i = 0; i < desc.n; i++) {
                    if (desc.p[i] == '\\') put_char('\\');
                    put_char(desc.p[i]);
                }
            }
            put_char('\n');
            break;

        case OUT_LINES:
            put_bytes(prefix, prefix_len);
            put_str(value);
            if (add_space) put_char(' ');
            put_char('\n');
            break;

        case OUT_PWSH:
            put_bytes(prefix, prefix_len);
            put_str(value);
            if (add_space) put_char(' ');
            put_char('\t');
            put_bytes(prefix, prefix_len);
            put_str(value);
            put_char('\t');
            put_char('0' + type);
            put_char('\t');
            put_str(desc.n > 0 ? desc : value);
            put_char('\n');
            break;

        case OUT_UNKNOWN:
            break;
    }
}

// Compare strings lexicographically (for binary search)
static inline int str_cmp(const char *a, size_t a_len, const char *b, size_t b_len) {
    size_t min_len = (a_len < b_len) ? a_len : b_len;
    int cmp = memcmp(a, b, min_len);
    if (cmp != 0) return cmp;
    return (a_len < b_len) ? -1 : (a_len > b_len) ? 1 : 0;
}

// Binary search for a command by name among sorted subcommands
static const Command *bsearch_command(const Command *subs, uint16_t count, const char *name, size_t name_len) {
    uint16_t lo = 0, hi = count;
    while (lo < hi) {
        uint16_t mid = lo + (hi - lo) / 2;
        String s = str_get(subs[mid].name_off);
        int cmp = str_cmp(s.p, s.n, name, name_len);
        if (cmp < 0) lo = mid + 1;
        else if (cmp > 0) hi = mid;
        else return &subs[mid];
    }
    return NULL;
}

// Maximum command path depth (root -> ... -> leaf)
#define MAX_CMD_DEPTH 64

// Command path from root to deepest match (for param inheritance)
static const Command *g_cmd_path[MAX_CMD_DEPTH];
static int g_cmd_path_len = 0;

// Find the deepest matching command, tracking the path
static const Command *find_command(void) {
    g_cmd_path_len = 0;
    const Command *cmd = get_root_command();
    g_cmd_path[g_cmd_path_len++] = cmd;
    int i = 1;  // Skip first arg (CLI name)

    while (i < g_span_count && cmd->subcommands_count > 0) {
        const char *arg = g_spans[i];

        if (arg[0] == '-') {
            i++;
            continue;
        }

        size_t arg_len = g_arg_lens[i];
        const Command *found = bsearch_command(cmd_subcommands(cmd), cmd->subcommands_count, arg, arg_len);

        if (found) {
            cmd = found;
            if (g_cmd_path_len < MAX_CMD_DEPTH) {
                g_cmd_path[g_cmd_path_len++] = cmd;
            }
            i++;
        } else {
            break;
        }
    }

    return cmd;
}

// Linear scan for small span counts - avoids 4KB memset overhead of hash table
static bool param_used_linear(const Param *param) {
    String name = str_get(param->name_off);
    String short_opt = param->short_off ? str_get(param->short_off) : (String){NULL, 0};

    for (int i = 0; i < g_span_count; i++) {
        if (g_spans[i][0] != '-') continue;
        size_t n = g_arg_lens[i];
        const char *span = g_spans[i];
        if (name.n > 0) {
            const char *eq = memchr(span, '=', n);
            size_t base_len = eq ? (size_t)(eq - span) : n;
            if (name.n == base_len && memcmp(name.p, span, base_len) == 0) return true;
        }
        if (short_opt.p && short_opt.n >= 2 && span[0] == '-' && span[1] != '-') {
            char short_ch = short_opt.p[1];
            if (span[1] == short_ch) return true;  // -o or -oVALUE
            if (!PARAM_TAKES_VALUE(param) && is_short_cluster_token(span, n)) {
                for (size_t j = 2; j < n; j++) {
                    if (span[j] == short_ch) return true;
                }
            }
        }
    }
    return false;
}

// Check if a parameter has already been used (by long or short name)
// Uses linear scan for small span counts, hash set for large
static bool param_used(const Param *param) {
    if (g_span_count <= USED_LINEAR_THRESHOLD) {
        return param_used_linear(param);
    }

    used_set_build();  // Lazy init on first call
    String name = str_get(param->name_off);
    if (name.n > 0 && used_set_contains(name.p, name.n)) return true;
    if (param->short_off) {
        String short_opt = str_get(param->short_off);
        if (short_opt.n >= 2 && g_used_short[(unsigned char)short_opt.p[1]]) return true;
    }
    return false;
}

// Pre-computed prefix analysis for parameter completion
typedef struct {
    size_t len;
    bool is_dash;         // starts with -
    bool is_double_dash;  // starts with --
    bool is_single_dash;  // starts with - but not --
} PrefixInfo;

static inline PrefixInfo make_prefix_info(const char *prefix, size_t len) {
    PrefixInfo info = {0};
    if (prefix && len > 0) {
        info.len = len;
        info.is_dash = prefix[0] == '-';
        info.is_double_dash = len >= 2 && prefix[0] == '-' && prefix[1] == '-';
        info.is_single_dash = info.is_dash && !info.is_double_dash;
    }
    return info;
}

// Prefix tokenization guard (single spaces only, no leading/double spaces)
static inline bool prefix_is_tokenizable(const char *prefix, size_t len) {
    if (!prefix || len == 0) return false;
    if (prefix[0] == ' ') return false;
    bool has_space = false;
    char prev = '\0';
    for (size_t i = 0; i < len; i++) {
        char c = prefix[i];
        if (c == '\t' || c == '\n' || c == '\r') return false;
        if (c == ' ') {
            if (prev == ' ') return false;
            has_space = true;
        }
        prev = c;
    }
    return has_space;
}

// Recursively output leaf commands
static void complete_leaf_commands(const Command *cmd, String path, const char *prefix, size_t prefix_len) {
    if (cmd->subcommands_count == 0) return;

    char *buf = path_buf;
    const Command *subs = cmd_subcommands(cmd);

    for (uint16_t i = 0; i < cmd->subcommands_count; i++) {
        const Command *sub = &subs[i];
        String sub_name = str_get(sub->name_off);

        size_t new_len;
        if (path.n > 0) {
            if (path.n + 1 + sub_name.n >= header.max_command_path_len) continue;
            buf[path.n] = ' ';
            memcpy(buf + path.n + 1, sub_name.p, sub_name.n);
            new_len = path.n + 1 + sub_name.n;
        } else {
            if (sub_name.n >= header.max_command_path_len) continue;
            memcpy(buf, sub_name.p, sub_name.n);
            new_len = sub_name.n;
        }
        buf[new_len] = '\0';

        bool matches = !prefix || strncmp(buf, prefix, prefix_len) == 0;

        if (sub->subcommands_count > 0) {
            if (!prefix || matches || strncmp(prefix, buf, new_len) == 0) {
                complete_leaf_commands(sub, (String){buf, new_len}, prefix, prefix_len);
            }
        } else if (matches) {
            uint32_t desc = !has_descriptions || output_format == OUT_LINES ? 0 : sub->desc_off;
            output_completion((String){buf, new_len}, str_get(desc), COMP_COMMAND);
        }

        buf[path.n] = '\0';
    }
}

// Prefix token-aware leaf completion (exact tokens via binary search, then DFS)
static void complete_leaf_commands_token_prefix(const Command *cmd, const char *prefix, size_t prefix_len) {
    if (!cmd || !prefix || prefix_len == 0) return;

    bool trailing_space = prefix[prefix_len - 1] == ' ';
    const char *p = prefix;
    const char *end = prefix + prefix_len;
    size_t path_len = 0;
    const Command *cur = cmd;

    path_buf[0] = '\0';

    while (p < end) {
        const char *start = p;
        while (p < end && *p != ' ') p++;
        size_t tok_len = (size_t)(p - start);
        if (tok_len == 0) {
            // Unexpected (e.g., double spaces); fall back to full scan
            complete_leaf_commands(cur, (String){path_buf, path_len}, prefix, prefix_len);
            return;
        }

        bool is_last = (p >= end);
        bool token_complete = trailing_space || !is_last;
        if (!token_complete) break;

        if (cur->subcommands_count == 0) return;
        const Command *found = bsearch_command(cmd_subcommands(cur), cur->subcommands_count, start, tok_len);
        if (!found) return;

        if (path_len > 0) {
            if (path_len + 1 + tok_len >= header.max_command_path_len) return;
            path_buf[path_len] = ' ';
            memcpy(path_buf + path_len + 1, start, tok_len);
            path_len += 1 + tok_len;
        } else {
            if (tok_len >= header.max_command_path_len) return;
            memcpy(path_buf, start, tok_len);
            path_len = tok_len;
        }
        path_buf[path_len] = '\0';

        cur = found;

        if (p < end && *p == ' ') p++;  // Skip single space delimiter
    }

    complete_leaf_commands(cur, (String){path_buf, path_len}, prefix, prefix_len);
}

// Binary search for first subcommand with name >= prefix (lower bound)
static uint16_t bsearch_prefix_lower(const Command *subs, uint16_t count,
                                      const char *prefix, size_t prefix_len) {
    uint16_t lo = 0, hi = count;
    while (lo < hi) {
        uint16_t mid = lo + (hi - lo) / 2;
        String s = str_get(subs[mid].name_off);
        size_t cmp_len = (s.n < prefix_len) ? s.n : prefix_len;
        int cmp = memcmp(s.p, prefix, cmp_len);
        if (cmp < 0 || (cmp == 0 && s.n < prefix_len)) {
            lo = mid + 1;
        } else {
            hi = mid;
        }
    }
    return lo;
}

// Complete immediate subcommands (single level)
// Uses binary search for prefix matching: O(log n + matches) instead of O(n)
static void complete_next_level(const Command *cmd, const char *prefix, size_t prefix_len) {
    if (cmd->subcommands_count == 0) return;

    const Command *subs = cmd_subcommands(cmd);

    // No prefix: output all subcommands
    if (!prefix || prefix_len == 0) {
        for (uint16_t i = 0; i < cmd->subcommands_count; i++) {
            const Command *sub = &subs[i];
            String name = str_get(sub->name_off);
            uint32_t desc = !has_descriptions || output_format == OUT_LINES ? 0 : sub->desc_off;
            output_completion(name, str_get(desc), COMP_COMMAND);
        }
        return;
    }

    // Binary search for first match, then iterate while prefix matches
    uint16_t start = bsearch_prefix_lower(subs, cmd->subcommands_count, prefix, prefix_len);
    for (uint16_t i = start; i < cmd->subcommands_count; i++) {
        const Command *sub = &subs[i];
        String name = str_get(sub->name_off);
        if (name.n < prefix_len || memcmp(name.p, prefix, prefix_len) != 0) break;
        uint32_t desc = !has_descriptions || output_format == OUT_LINES ? 0 : sub->desc_off;
        output_completion(name, str_get(desc), COMP_COMMAND);
    }
}

// Complete subcommands (full leaf paths or next level based on flag)
static void complete_subcommands(const Command *cmd, const char *prefix, size_t prefix_len) {
    if (full_commands) {
        if (prefix_is_tokenizable(prefix, prefix_len)) {
            complete_leaf_commands_token_prefix(cmd, prefix, prefix_len);
        } else {
            path_buf[0] = '\0';
            complete_leaf_commands(cmd, (String){path_buf, 0}, prefix, prefix_len);
        }
    } else {
        complete_next_level(cmd, prefix, prefix_len);
    }
}

// Complete parameters from a param list
static void complete_params_list(const Param *params, uint16_t params_count,
                                  const char *prefix, const PrefixInfo *pinfo) {
    if (!params || params_count == 0) return;
    if (pinfo->len > 0 && !pinfo->is_dash) return;

    // When prefix is "-" (single dash only), show short options first
    if (pinfo->is_single_dash) {
        for (uint16_t i = 0; i < params_count; i++) {
            const Param *p = &params[i];
            if (p->short_off == 0) continue;
            if (param_used(p)) continue;

            String short_opt = str_get(p->short_off);
            if (short_opt.n >= pinfo->len && memcmp(short_opt.p, prefix, pinfo->len) == 0) {
                uint32_t desc = !has_descriptions || output_format == OUT_LINES ? 0 : p->desc_off;
                if (!g_emit_set_ready) emit_set_reset();
                if (!emit_set_contains(short_opt.p, short_opt.n)) {
                    output_completion(short_opt, str_get(desc), COMP_PARAM_NAME);
                    emit_set_add(short_opt.p, short_opt.n);
                }
            }
        }
    }

    // Show long options (always, unless prefix is single dash with more chars like "-x")
    if (!pinfo->is_single_dash || pinfo->len == 1) {
        for (uint16_t i = 0; i < params_count; i++) {
            const Param *p = &params[i];
            if (param_used(p)) continue;

            String name = str_get(p->name_off);
            if (name.n == 0) continue;  // Skip short-only params
            if (pinfo->len == 0 || (name.n >= pinfo->len && memcmp(name.p, prefix, pinfo->len) == 0)) {
                uint32_t desc = !has_descriptions || output_format == OUT_LINES ? 0 : p->desc_off;
                if (!g_emit_set_ready) emit_set_reset();
                if (!emit_set_contains(name.p, name.n)) {
                    output_completion(name, str_get(desc), COMP_PARAM_NAME);
                    emit_set_add(name.p, name.n);
                }
            }
        }
    }
}

// Complete string list at a blob offset (choices or members)
static void complete_string_list(uint32_t off, const char *prefix, size_t prefix_len) {
    if (off == 0) return;

    uint16_t count = get_string_list_count(off);
    const uint32_t *offsets = get_string_offsets(off);

    for (uint16_t i = 0; i < count; i++) {
        String s = str_get(offsets[i]);
        if (!prefix || (s.n >= prefix_len && memcmp(s.p, prefix, prefix_len) == 0)) {
            output_completion(s, str_get(0), COMP_PARAM_VALUE);
        }
    }
}

static void complete_string_list_prefixed(uint32_t off, const char *prefix, size_t prefix_len,
                                          String out_prefix) {
    if (off == 0) return;

    uint16_t count = get_string_list_count(off);
    const uint32_t *offsets = get_string_offsets(off);

    for (uint16_t i = 0; i < count; i++) {
        String s = str_get(offsets[i]);
        if (!prefix || (s.n >= prefix_len && memcmp(s.p, prefix, prefix_len) == 0)) {
            output_completion_prefixed(out_prefix.p, out_prefix.n, s, str_get(0), COMP_PARAM_VALUE);
        }
    }
}

static bool parse_escape_char(const char **pp, char *out, const char **err_msg) {
    const char *p = *pp;
    if (!p || !*p) {
        if (err_msg) *err_msg = "unterminated escape";
        return false;
    }
    char c = *p++;
    switch (c) {
        case 'n': *out = '\n'; break;
        case 'r': *out = '\r'; break;
        case 't': *out = '\t'; break;
        case 'v': *out = '\v'; break;
        case 'b': *out = '\b'; break;
        case 'a': *out = '\a'; break;
        case 'f': *out = '\f'; break;
        case '\\': *out = '\\'; break;
        case '"': *out = '"'; break;
        case '\'': *out = '\''; break;
        case 'x':
            if (isxdigit((unsigned char)p[0]) && isxdigit((unsigned char)p[1])) {
                int hi = isdigit((unsigned char)p[0]) ? p[0] - '0' : (tolower((unsigned char)p[0]) - 'a' + 10);
                int lo = isdigit((unsigned char)p[1]) ? p[1] - '0' : (tolower((unsigned char)p[1]) - 'a' + 10);
                *out = (char)((hi << 4) | lo);
                p += 2;
            } else {
                *out = 'x';
            }
            break;
        default:
            *out = c;
            break;
    }
    *pp = p;
    return true;
}

// Split command string into argv array (space-separated, supports quotes + escapes)
// Returns argc, fills argv (must have room for max_args+1 entries, last is NULL)
// On error, returns -1 and sets err_msg.
static int split_args(char *cmd, char **argv, int max_args, const char **err_msg) {
    int argc = 0;
    char *p = cmd;
    if (err_msg) *err_msg = NULL;
    while (*p && argc < max_args) {
        while (*p == ' ' || *p == '\t') p++;  // Skip whitespace
        if (!*p) break;

        char *w = p;
        argv[argc++] = w;

        while (*p && *p != ' ' && *p != '\t') {
            if (*p == '\'') {
                p++;
                while (*p && *p != '\'') {
                    *w++ = *p++;
                }
                if (*p != '\'') {
                    if (err_msg) *err_msg = "unterminated quote";
                    return -1;
                }
                p++;
                continue;
            }
            if (*p == '"') {
                p++;
                while (*p && *p != '"') {
                    if (*p == '\\') {
                        const char *esc = p + 1;
                        char out;
                        if (!parse_escape_char(&esc, &out, err_msg)) return -1;
                        *w++ = out;
                        p = (char *)esc;
                        continue;
                    }
                    *w++ = *p++;
                }
                if (*p != '"') {
                    if (err_msg) *err_msg = "unterminated quote";
                    return -1;
                }
                p++;
                continue;
            }
            if (*p == '\\') {
                const char *esc = p + 1;
                char out;
                if (!parse_escape_char(&esc, &out, err_msg)) return -1;
                *w++ = out;
                p = (char *)esc;
                continue;
            }
            *w++ = *p++;
        }
        *w = '\0';
        if (*p == ' ' || *p == '\t') p++;
    }
    while (*p == ' ' || *p == '\t') p++;
    if (*p) {
        if (err_msg) *err_msg = "too many arguments (max 62)";
        return -1;
    }
    argv[argc] = NULL;
    return argc;
}

#ifdef _WIN32
static bool cmdline_buf_append(char **buf, size_t *len, size_t *cap, const char *s, size_t n) {
    if (*len + n + 1 > *cap) {
        size_t next = (*cap > 0) ? *cap : 128;
        while (*len + n + 1 > next) next *= 2;
        char *tmp = realloc(*buf, next);
        if (!tmp) return false;
        *buf = tmp;
        *cap = next;
    }
    memcpy(*buf + *len, s, n);
    *len += n;
    (*buf)[*len] = '\0';
    return true;
}

static bool cmdline_buf_append_char(char **buf, size_t *len, size_t *cap, char c) {
    return cmdline_buf_append(buf, len, cap, &c, 1);
}

static bool win_cmdline_append_arg(char **buf, size_t *len, size_t *cap, const char *arg) {
    if (*len > 0) {
        if (!cmdline_buf_append_char(buf, len, cap, ' ')) return false;
    }
    bool need_quotes = false;
    if (!*arg) need_quotes = true;
    for (const char *p = arg; *p; p++) {
        if (*p == ' ' || *p == '\t' || *p == '"') {
            need_quotes = true;
            break;
        }
    }
    if (!need_quotes) {
        return cmdline_buf_append(buf, len, cap, arg, strlen(arg));
    }

    if (!cmdline_buf_append_char(buf, len, cap, '"')) return false;
    size_t bs_count = 0;
    for (const char *p = arg; ; p++) {
        char c = *p;
        if (c == '\\') {
            bs_count++;
            continue;
        }
        if (c == '"') {
            for (size_t i = 0; i < bs_count * 2 + 1; i++) {
                if (!cmdline_buf_append_char(buf, len, cap, '\\')) return false;
            }
            if (!cmdline_buf_append_char(buf, len, cap, '"')) return false;
            bs_count = 0;
            continue;
        }
        if (c == '\0') {
            for (size_t i = 0; i < bs_count * 2; i++) {
                if (!cmdline_buf_append_char(buf, len, cap, '\\')) return false;
            }
            if (!cmdline_buf_append_char(buf, len, cap, '"')) return false;
            break;
        }
        for (size_t i = 0; i < bs_count; i++) {
            if (!cmdline_buf_append_char(buf, len, cap, '\\')) return false;
        }
        bs_count = 0;
        if (!cmdline_buf_append_char(buf, len, cap, c)) return false;
    }
    return true;
}

static char *build_windows_cmdline(char *const *argv) {
    size_t len = 0;
    size_t cap = 0;
    char *buf = NULL;
    for (size_t i = 0; argv[i]; i++) {
        if (!win_cmdline_append_arg(&buf, &len, &cap, argv[i])) {
            free(buf);
            return NULL;
        }
    }
    return buf;
}
#endif

static void completer_line_finish(CompleterCacheEntry *store_entry, const char *line, size_t line_pos,
                                  const char *prefix, size_t prefix_len,
                                  bool truncated, bool *warned) {
    if (truncated) {
        if (warned && !*warned && stdout_is_tty()) {
            fprintf(stderr, "fast-completer: completer output line too long, dropping\n");
            *warned = true;
        }
        return;
    }
    if (line_pos == 0) return;
    if (!prefix || (line_pos >= prefix_len && memcmp(line, prefix, prefix_len) == 0)) {
        completer_cache_add_value(store_entry, line, line_pos);
    }
}

// Execute a dynamic completer command and output results
// cli_name: CLI name (e.g., "az") from g_spans[0]
// completer: subcommand args (e.g., "aks get-versions --output tsv") - String with length
// prefix: optional prefix to filter results
// prefix_len: length of prefix
// out_prefix: optional prefix to prepend to emitted values (e.g., "--opt=")
static void execute_completer(const char *cli_name, String completer,
                               const char *prefix, size_t prefix_len, String out_prefix) {
    if (!cli_name || !completer.p || completer.n == 0) return;

    CompleterCacheEntry *cache_entry = completer_cache_find(cli_name, completer, prefix, prefix_len);
    if (cache_entry) {
        completer_cache_emit(cache_entry, out_prefix);
        return;
    }
    cache_entry = completer_cache_add(cli_name, completer, prefix, prefix_len);
    CompleterCacheEntry temp_entry = {0};
    CompleterCacheEntry *store_entry = cache_entry ? cache_entry : &temp_entry;
    bool timed_out = false;
    bool ok = false;

    char *args = NULL;
#ifdef _WIN32
    char *cmdline = NULL;
    HANDLE stdout_read = INVALID_HANDLE_VALUE;
    HANDLE stdout_write = INVALID_HANDLE_VALUE;
    HANDLE event_handle = NULL;
    PROCESS_INFORMATION pi = {0};
#else
    int pipefd[2] = {-1, -1};
    posix_spawn_file_actions_t actions;
    bool actions_init = false;
    pid_t pid = -1;
#endif

    // Build argument string: copy completer (need mutable string for splitting)
    args = malloc(completer.n + 1);
    if (!args) goto cleanup;
    memcpy(args, completer.p, completer.n);
    args[completer.n] = '\0';

    // Split into argv: [cli_name, arg1, arg2, ..., NULL]
    char *argv[64];
    argv[0] = (char *)cli_name;
    const char *split_err = NULL;
    if (split_args(args, argv + 1, 62, &split_err) < 0) {
        if (split_err) {
            fprintf(stderr, "fast-completer: invalid completer args for '%s': %s\n",
                    cli_name ? cli_name : "(unknown)", split_err);
        } else {
            fprintf(stderr, "fast-completer: invalid completer args for '%s'\n",
                    cli_name ? cli_name : "(unknown)");
        }
        goto cleanup;
    }

#ifdef _WIN32
    // Windows implementation using overlapped I/O with direct exec (no cmd.exe shell)

    // Build command line string from argv for CreateProcess
    cmdline = build_windows_cmdline(argv);
    if (!cmdline) goto cleanup;

    // Create named pipe with FILE_FLAG_OVERLAPPED for async reads
    char pipe_name[256];
    snprintf(pipe_name, sizeof(pipe_name), "\\\\.\\pipe\\fc_%lu_%lu",
             (unsigned long)GetCurrentProcessId(), (unsigned long)GetTickCount());

    stdout_read = CreateNamedPipeA(
        pipe_name, PIPE_ACCESS_INBOUND | FILE_FLAG_OVERLAPPED,
        PIPE_TYPE_BYTE | PIPE_WAIT, 1, 4096, 4096, 0, NULL);
    if (stdout_read == INVALID_HANDLE_VALUE) goto cleanup;

    SECURITY_ATTRIBUTES sa = { sizeof(SECURITY_ATTRIBUTES), NULL, TRUE };
    stdout_write = CreateFileA(pipe_name, GENERIC_WRITE, 0, &sa, OPEN_EXISTING, 0, NULL);
    if (stdout_write == INVALID_HANDLE_VALUE) goto cleanup;

    STARTUPINFOA si = {0};
    si.cb = sizeof(STARTUPINFOA);
    si.dwFlags = STARTF_USESTDHANDLES | STARTF_USESHOWWINDOW;
    si.hStdOutput = stdout_write;
    si.hStdError = GetStdHandle(STD_ERROR_HANDLE);
    si.hStdInput = GetStdHandle(STD_INPUT_HANDLE);
    si.wShowWindow = SW_HIDE;

    if (!CreateProcessA(NULL, cmdline, NULL, NULL, TRUE, CREATE_NO_WINDOW, NULL, NULL, &si, &pi)) {
        goto cleanup;
    }
    CloseHandle(stdout_write);  // Child has it, close so reads see EOF when child exits
    stdout_write = INVALID_HANDLE_VALUE;

    // Overlapped read setup
    OVERLAPPED ov = {0};
    ov.hEvent = CreateEvent(NULL, TRUE, FALSE, NULL);
    if (!ov.hEvent) {
        TerminateProcess(pi.hProcess, 1);
        goto cleanup;
    }
    event_handle = ov.hEvent;

    char line[4096];
    size_t line_pos = 0;
    bool line_truncated = false;
    bool trunc_warned = false;
    char buf[4096];
    DWORD bytes_read = 0;
    ULONGLONG start_time = GetTickCount64();
    HANDLE wait_handles[2] = {ov.hEvent, pi.hProcess};

    while (1) {
        ULONGLONG elapsed = GetTickCount64() - start_time;
        DWORD remaining = (elapsed >= (ULONGLONG)g_completer_timeout_ms) ? 0 : (DWORD)(g_completer_timeout_ms - elapsed);

        ResetEvent(ov.hEvent);
        BOOL read_ok = ReadFile(stdout_read, buf, sizeof(buf), &bytes_read, &ov);
        DWORD err = GetLastError();

        if (!read_ok && err == ERROR_IO_PENDING) {
            DWORD wait = WaitForMultipleObjects(2, wait_handles, FALSE, remaining);
            if (wait == WAIT_OBJECT_0) {
                if (!GetOverlappedResult(stdout_read, &ov, &bytes_read, FALSE)) break;
            } else if (wait == WAIT_OBJECT_0 + 1) {
                CancelIo(stdout_read);
                if (!GetOverlappedResult(stdout_read, &ov, &bytes_read, FALSE) || bytes_read == 0) break;
            } else if (wait == WAIT_TIMEOUT) {
                CancelIo(stdout_read);
                TerminateProcess(pi.hProcess, 1);
                timed_out = true;
                break;
            } else {
                CancelIo(stdout_read);
                TerminateProcess(pi.hProcess, 1);
                break;
            }
        } else if (!read_ok) {
            break;
        }

        for (DWORD i = 0; i < bytes_read; i++) {
            if (buf[i] == '\n' || buf[i] == '\r') {
                completer_line_finish(store_entry, line, line_pos, prefix, prefix_len, line_truncated, &trunc_warned);
                line_pos = 0;
                line_truncated = false;
            } else if (!line_truncated) {
                if (line_pos < sizeof(line) - 1) {
                    line[line_pos++] = buf[i];
                } else {
                    line_truncated = true;
                }
            }
        }
    }

    completer_line_finish(store_entry, line, line_pos, prefix, prefix_len, line_truncated, &trunc_warned);
#else
    // Unix implementation using posix_spawnp with direct exec (no shell)
    if (pipe(pipefd) < 0) goto cleanup;

    if (posix_spawn_file_actions_init(&actions) != 0) goto cleanup;
    actions_init = true;
    posix_spawn_file_actions_addclose(&actions, pipefd[0]);
    posix_spawn_file_actions_adddup2(&actions, pipefd[1], STDOUT_FILENO);
    posix_spawn_file_actions_addclose(&actions, pipefd[1]);
    posix_spawn_file_actions_addopen(&actions, STDERR_FILENO, "/dev/null", O_WRONLY, 0);

    extern char **environ;
    if (posix_spawnp(&pid, cli_name, &actions, NULL, argv, environ) != 0) goto cleanup;
    close(pipefd[1]);  // Close write end so reads see EOF when child exits
    pipefd[1] = -1;

    // Non-blocking reads with poll() timeout
    fcntl(pipefd[0], F_SETFL, fcntl(pipefd[0], F_GETFL) | O_NONBLOCK);

    char line[4096];
    size_t line_pos = 0;
    bool line_truncated = false;
    bool trunc_warned = false;
    char buf[4096];
    struct timespec start, now;
    clock_gettime(CLOCK_MONOTONIC, &start);
    int timeout_ms = g_completer_timeout_ms;

    while (timeout_ms > 0) {
        struct pollfd pfd = { .fd = pipefd[0], .events = POLLIN };
        int poll_res = poll(&pfd, 1, timeout_ms);
        if (poll_res == 0) { timed_out = true; break; }
        if (poll_res < 0) break;

        ssize_t n = read(pipefd[0], buf, sizeof(buf));
        if (n <= 0) break;

        for (ssize_t i = 0; i < n; i++) {
            if (buf[i] == '\n') {
                completer_line_finish(store_entry, line, line_pos, prefix, prefix_len, line_truncated, &trunc_warned);
                line_pos = 0;
                line_truncated = false;
            } else if (!line_truncated) {
                if (line_pos < sizeof(line) - 1) {
                    line[line_pos++] = buf[i];
                } else {
                    line_truncated = true;
                }
            }
        }

        // Update remaining timeout
        clock_gettime(CLOCK_MONOTONIC, &now);
        int elapsed_ms = (now.tv_sec - start.tv_sec) * 1000 + (now.tv_nsec - start.tv_nsec) / 1000000;
        timeout_ms = g_completer_timeout_ms - elapsed_ms;
    }

    completer_line_finish(store_entry, line, line_pos, prefix, prefix_len, line_truncated, &trunc_warned);

    if (pid > 0 && waitpid(pid, NULL, WNOHANG) == 0) {
        kill(pid, SIGKILL);
        waitpid(pid, NULL, 0);  // Reap zombie
    }
#endif

    ok = !timed_out;

cleanup:
    if (timed_out && stdout_is_tty()) {
        fprintf(stderr, "fast-completer: completer timed out for '%s'\n", cli_name);
    }
    if (!ok) {
        if (cache_entry) {
            completer_cache_remove(cache_entry);
        } else {
            completer_cache_free_values(&temp_entry);
        }
    } else {
        if (store_entry) {
            completer_cache_emit(store_entry, out_prefix);
        }
        if (!cache_entry) {
            completer_cache_free_values(&temp_entry);
        }
    }
    free(args);
#ifdef _WIN32
    if (event_handle) CloseHandle(event_handle);
    if (stdout_read != INVALID_HANDLE_VALUE) CloseHandle(stdout_read);
    if (stdout_write != INVALID_HANDLE_VALUE) CloseHandle(stdout_write);
    if (pi.hThread) CloseHandle(pi.hThread);
    if (pi.hProcess) CloseHandle(pi.hProcess);
    free(cmdline);
#else
    if (pipefd[0] != -1) close(pipefd[0]);
    if (pipefd[1] != -1) close(pipefd[1]);
    if (actions_init) posix_spawn_file_actions_destroy(&actions);
#endif
    return;
}

// Find a parameter by name (long or short option) using linear search
// Linear search is used because we must check both long AND short names,
// and typical param count per command is small (< 10)
static const Param *find_param(const Param *params, uint16_t params_count, const char *opt, size_t opt_len) {
    if (!params || params_count == 0 || !opt) return NULL;
    if (opt[0] != '-') return NULL;

    bool is_short = (opt_len == 2 && opt[0] == '-' && opt[1] != '-');

    for (uint16_t i = 0; i < params_count; i++) {
        // Check long option
        String s = str_get(params[i].name_off);
        if (s.n == opt_len && memcmp(s.p, opt, opt_len) == 0)
            return &params[i];

        // Check short option
        if (is_short && params[i].short_off) {
            String short_opt = str_get(params[i].short_off);
            if (short_opt.n == opt_len && memcmp(short_opt.p, opt, opt_len) == 0)
                return &params[i];
        }
    }
    return NULL;
}

// Complete params from entire command path (deepest first for relevance)
static void complete_path_params(const char *prefix, const PrefixInfo *pinfo) {
    for (int i = g_cmd_path_len - 1; i >= 0; i--) {
        const Command *cmd = g_cmd_path[i];
        complete_params_list(cmd_params(cmd), cmd->params_count, prefix, pinfo);
    }
}

// Find a param by name across entire command path (deepest first for override semantics)
static const Param *find_path_param(const char *opt, size_t opt_len) {
    for (int i = g_cmd_path_len - 1; i >= 0; i--) {
        const Command *cmd = g_cmd_path[i];
        const Param *p = find_param(cmd_params(cmd), cmd->params_count, opt, opt_len);
        if (p) return p;
    }
    return NULL;
}

// Check if span is empty/whitespace
static inline bool is_new_arg(const char *span) {
    if (!span || !*span) return true;
    // Fast path: if first char is not whitespace, it's not a new arg
    if (span[0] != ' ' && span[0] != '\t') return false;
    // Slow path: check remaining chars for non-whitespace
    for (const char *p = span + 1; *p; p++) {
        if (*p != ' ' && *p != '\t') return false;
    }
    return true;
}

// Parse output format - uses first char + length for fast dispatch
static OutputFormat parse_format(const char *name) {
    String s = {name, strlen(name)};
    #define FMT(lit) STR_EQ_LIT(s, lit)
    switch (s.p[0]) {
        case 'b': if (FMT("bash")) return OUT_LINES; break;
        case 'f': if (FMT("fish")) return OUT_TSV; break;
        case 'j': if (FMT("json")) return OUT_JSON; break;
        case 'l': if (FMT("lines")) return OUT_LINES; break;
        case 'p': if (FMT("pwsh") || FMT("powershell")) return OUT_PWSH; break;
        case 't': if (FMT("tsv")) return OUT_TSV; break;
        case 'z': if (FMT("zsh")) return OUT_ZSH; break;
    }
    #undef FMT
    return OUT_UNKNOWN;
}

// Maximum spans we support (command lines rarely exceed this)
#define MAX_SPANS 128

// Main completion logic
static void complete(int nspans, const char **spans) {
    if (nspans == 0) {
        if (output_format == OUT_JSON) put_lit("[]\n");
        return;
    }

    // Fail if too many spans
    if (nspans > MAX_SPANS) {
        fprintf(stderr, "Too many arguments (%d > %d)\n", nspans, MAX_SPANS);
        exit(1);
    }

    // Pre-compute all arg lengths once and set globals (fixed-size to avoid VLA)
    // Exploit contiguous argv layout (works on Linux, macOS, Windows, BSDs)
    size_t arg_lens[MAX_SPANS];
    for (int i = 0; i < nspans - 1; i++) {
        arg_lens[i] = (size_t)(spans[i + 1] - spans[i] - 1);
    }
    arg_lens[nspans - 1] = strlen(spans[nspans - 1]);
    g_spans = spans;
#if defined(__GNUC__) && !defined(__clang__)
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wdangling-pointer"
#endif
    g_arg_lens = arg_lens;  // Safe: only accessed during complete()'s lifetime
#if defined(__GNUC__) && !defined(__clang__)
#pragma GCC diagnostic pop
#endif
    g_span_count = nspans > 1 ? nspans - 1 : 1;
    g_used_set_ready = false;  // Reset for lazy init
    g_used_short_ready = false;
    g_emit_set_ready = false;

    // Find the deepest matching command
    const Command *cmd = find_command();

    if (output_format == OUT_JSON) put_char('[');

    const char *last_span = spans[nspans - 1];
    size_t last_span_len = arg_lens[nspans - 1];
    bool is_empty = is_new_arg(last_span);
    bool is_flag_prefix = last_span[0] == '-';
    char c = last_span[0];
    bool is_cmd_prefix = (c >= 'a' && c <= 'z') || (c >= 'A' && c <= 'Z') ||
                         (c >= '0' && c <= '9') || c == '_';

    if (is_flag_prefix) {
        const char *eq = memchr(last_span, '=', last_span_len);
        if (eq && eq > last_span) {
            size_t opt_len = (size_t)(eq - last_span);
            const Param *param = find_path_param(last_span, opt_len);
            if (param && PARAM_TAKES_VALUE(param)) {
                String out_prefix = {last_span, opt_len + 1};
                const char *val_prefix = eq + 1;
                size_t val_len = last_span_len - opt_len - 1;
                if (PARAM_HAS_CHOICES(param)) {
                    complete_string_list_prefixed(param->choices_off, val_prefix, val_len, out_prefix);
                } else if (PARAM_HAS_MEMBERS(param)) {
                    complete_string_list_prefixed(param->choices_off, val_prefix, val_len, out_prefix);
                } else if (PARAM_HAS_COMPLETER(param)) {
                    execute_completer(g_spans[0], str_get(param->choices_off), val_prefix, val_len, out_prefix);
                }
                if (output_format == OUT_JSON) put_lit("]\n");
                return;
            }
        }
        PrefixInfo pinfo = make_prefix_info(last_span, last_span_len);
        complete_path_params(last_span, &pinfo);
        if (output_format == OUT_JSON) put_lit("]\n");
        return;
    }

    if (is_cmd_prefix) {
        if (cmd->subcommands_count > 0) {
            complete_subcommands(cmd, last_span, last_span_len);
        }
        if (output_format == OUT_JSON) put_lit("]\n");
        return;
    }

    if (!is_empty) {
        if (output_format == OUT_JSON) put_lit("]\n");
        return;
    }

    const char *prev_arg = g_span_count > 0 ? spans[g_span_count - 1] : "";

    if (prev_arg[0] == '-') {
        size_t prev_len = arg_lens[g_span_count - 1];

        const Param *param = find_path_param(prev_arg, prev_len);
        if (param && PARAM_TAKES_VALUE(param)) {
            if (PARAM_HAS_CHOICES(param)) {
                complete_string_list(param->choices_off, NULL, 0);
            } else if (PARAM_HAS_MEMBERS(param)) {
                complete_string_list(param->choices_off, NULL, 0);
            } else if (PARAM_HAS_COMPLETER(param)) {
                execute_completer(g_spans[0], str_get(param->choices_off), NULL, 0, (String){NULL, 0});
            }
            if (output_format == OUT_JSON) put_lit("]\n");
            return;
        }
    }

    if (cmd->subcommands_count > 0) {
        complete_subcommands(cmd, NULL, 0);
    }

    PrefixInfo pinfo = {0};  // Empty prefix
    complete_path_params(NULL, &pinfo);

    if (output_format == OUT_JSON) put_lit("]\n");
}

// Load and validate blob file
static bool load_blob(const char *path) {
#ifdef _WIN32
    HANDLE fh = CreateFileA(path, GENERIC_READ, FILE_SHARE_READ,
                            NULL, OPEN_EXISTING, FILE_ATTRIBUTE_NORMAL, NULL);
    if (fh == INVALID_HANDLE_VALUE) {
        fprintf(stderr, "%s: %lu\n", path, GetLastError());
        return false;
    }

    LARGE_INTEGER size;
    if (!GetFileSizeEx(fh, &size)) {
        fprintf(stderr, "GetFileSizeEx: %lu\n", GetLastError());
        return false;
    }
    size_t blob_size = (size_t)size.QuadPart;

    if (blob_size < HEADER_SIZE) {
        fprintf(stderr, "%s: file too small\n", path);
        return false;
    }

    HANDLE mapping = CreateFileMappingA(fh, NULL, PAGE_READONLY, 0, 0, NULL);
    if (!mapping) {
        fprintf(stderr, "CreateFileMapping: %lu\n", GetLastError());
        return false;
    }

    blob = MapViewOfFile(mapping, FILE_MAP_READ, 0, 0, 0);
    if (!blob) {
        fprintf(stderr, "MapViewOfFile: %lu\n", GetLastError());
        CloseHandle(mapping);
        CloseHandle(fh);
        return false;
    }
    CloseHandle(mapping);  // Mapping remains valid until UnmapViewOfFile
    CloseHandle(fh);       // File handle no longer needed
#else
    int fd = open(path, O_RDONLY);
    if (fd < 0) {
        perror(path);
        return false;
    }

    struct stat st;
    if (fstat(fd, &st) < 0) {
        perror("fstat");
        return false;
    }

    size_t blob_size = st.st_size;
    if (blob_size < HEADER_SIZE) {
        fprintf(stderr, "%s: file too small\n", path);
        return false;
    }

    blob = mmap(NULL, blob_size, PROT_READ, MAP_PRIVATE, fd, 0);
    close(fd);  // fd no longer needed after mmap
    if (blob == MAP_FAILED) {
        perror("mmap");
        blob = NULL;
        return false;
    }
#endif

    // Validate magic
    if (memcmp(blob, BLOB_MAGIC, 4) != 0) {
        fprintf(stderr, "%s: invalid magic\n", path);
        return false;
    }

    // Check endianness compatibility BEFORE reading other fields.
    // HEADER_FLAG_BIG_ENDIAN should appear in the low byte for little-endian blobs,
    // and in the high byte for big-endian blobs.
    uint8_t flags_lo = blob[6];
    uint8_t flags_hi = blob[7];
    bool flag_le = (flags_lo & HEADER_FLAG_BIG_ENDIAN) != 0;
    bool flag_be = (flags_hi & HEADER_FLAG_BIG_ENDIAN) != 0;
    if (flag_le && flag_be) {
        fprintf(stderr, "%s: invalid flags (both endian markers set)\n", path);
        return false;
    }
    bool blob_is_big_endian = flag_be;
    bool system_is_big_endian = (*(uint16_t *)"\0\1" == 1);
    if (blob_is_big_endian != system_is_big_endian) {
        fprintf(stderr, "%s: endianness mismatch (blob is %s-endian, system is %s-endian)\n",
                path,
                blob_is_big_endian ? "big" : "little",
                system_is_big_endian ? "big" : "little");
        return false;
    }

    // Validate version (now safe to read as native endianness)
    uint16_t version = *(uint16_t *)(blob + 4);
    if (version != BLOB_VERSION) {
        fprintf(stderr, "%s: unsupported version %d (expected %d)\n", path, version, BLOB_VERSION);
        return false;
    }

    // Check if blob has descriptions
    uint16_t flags = *(uint16_t *)(blob + 6);
    has_descriptions = !(flags & HEADER_FLAG_NO_DESCRIPTIONS);

    // Parse header (skip magic:4, version:2, flags:2 = offset 8)
    const uint32_t *h = (const uint32_t *)(blob + 8);
    header.max_command_path_len = h[0];
    // h[1]-h[5] are counts/sizes (used by scripts/dump_blob.py, not runtime)
    header.string_table_off = h[6];
    header.commands_off = h[7];
    header.params_off = h[8];
    // h[9]-h[10] are choices_off, members_off (used by scripts/dump_blob.py)
    header.root_command_off = h[11];

    return true;
}


// --------------------------------------------------------------------------
// Cache directory management
// --------------------------------------------------------------------------

// Get cache directory path
static char *get_cache_dir(void) {
    // Check for custom cache directory
    const char *custom = getenv("FAST_COMPLETER_CACHE");
    if (custom && *custom) {
        return strdup(custom);
    }

    // Fall back to platform-specific default
    char *dir = NULL;

#ifdef _WIN32
    const char *localappdata = getenv("LOCALAPPDATA");
    if (localappdata) {
        size_t len = strlen(localappdata) + 20;
        dir = malloc(len);
        snprintf(dir, len, "%s\\fast-completer", localappdata);
    }
#else
    const char *home = getenv("HOME");
    if (home) {
        size_t len = strlen(home) + 30;
        dir = malloc(len);
        snprintf(dir, len, "%s/.cache/fast-completer", home);
    }
#endif

    return dir;
}

// Create cache directory if it doesn't exist
static bool ensure_cache_dir(void) {
    char *cache_dir = get_cache_dir();
    if (!cache_dir) return false;

#ifdef _WIN32
    // Create fast-completer directory under %LOCALAPPDATA%
    if (!CreateDirectoryA(cache_dir, NULL) && GetLastError() != ERROR_ALREADY_EXISTS) {
        fprintf(stderr, "Failed to create cache directory: %s (error %lu)\n", cache_dir, GetLastError());
        return false;
    }
#else
    // Create ~/.cache if needed, then ~/.cache/fast-completer
    char *parent = strdup(cache_dir);
    char *last_slash = strrchr(parent, '/');
    if (last_slash) {
        *last_slash = '\0';
        if (mkdir(parent, 0755) != 0 && errno != EEXIST) {
            fprintf(stderr, "Failed to create parent directory: %s: %s\n", parent, strerror(errno));
            return false;
        }
    }
    if (mkdir(cache_dir, 0755) != 0 && errno != EEXIST) {
        fprintf(stderr, "Failed to create cache directory: %s: %s\n", cache_dir, strerror(errno));
        return false;
    }
#endif

    return true;
}

// Build full blob path in cache directory
static char *build_cache_path(const char *name) {
    char *cache_dir = get_cache_dir();
    if (!cache_dir) return NULL;

    size_t len = strlen(cache_dir) + strlen(name) + 10;
    char *path = malloc(len);
#ifdef _WIN32
    snprintf(path, len, "%s\\%s.fcmpb", cache_dir, name);
#else
    snprintf(path, len, "%s/%s.fcmpb", cache_dir, name);
#endif

    return path;
}

// Check if path looks like a simple name (no slashes)
static bool is_simple_name(const char *path) {
    while (*path) {
        if (*path == '/' || *path == '\\') return false;
        path++;
    }
    return true;
}

// Resolve blob path: if simple name, look in cache; otherwise use as-is
static char *resolve_blob_path(const char *blob_arg) {
    // If it contains path separators, use as-is
    if (!is_simple_name(blob_arg)) {
        return strdup(blob_arg);
    }

    // Strip .fcmpb extension if present
    char *name = strdup(blob_arg);
    size_t len = strlen(name);
    if (len > 6 && strcmp(name + len - 6, ".fcmpb") == 0) {
        name[len - 6] = '\0';
    }

    char *path = build_cache_path(name);
    return path;
}

// Dump blob header for debugging
static void dump_header(const char *path) {
    const uint32_t *h = (const uint32_t *)(blob + 8);
    uint16_t version = *(uint16_t *)(blob + 4);
    uint16_t flags = *(uint16_t *)(blob + 6);

    printf("path: %s\n", path);
    printf("magic: %.4s\n", (const char *)blob);
    printf("version: %u\n", version);
    printf("flags: %u", flags);
    if (flags) {
        printf(" (");
        if (flags & HEADER_FLAG_BIG_ENDIAN) printf("big_endian");
        if (flags & HEADER_FLAG_NO_DESCRIPTIONS) {
            if (flags & HEADER_FLAG_BIG_ENDIAN) printf(", ");
            printf("no_descriptions");
        }
        printf(")");
    }
    printf("\n");
    printf("max_command_path_len: %u\n", h[0]);
    printf("command_count: %u\n", h[1]);
    printf("param_count: %u\n", h[2]);
    printf("string_table_size: %u\n", h[3]);
    printf("choices_count: %u\n", h[4]);
    printf("members_count: %u\n", h[5]);
    printf("string_table_off: %u\n", h[6]);
    printf("commands_off: %u\n", h[7]);
    printf("params_off: %u\n", h[8]);
    printf("choices_off: %u\n", h[9]);
    printf("members_off: %u\n", h[10]);
    printf("root_command_off: %u\n", h[11]);
}

static void print_help(void) {
    puts("fast-completer - Universal fast completion provider\n");
    puts("Usage: fast-completer [options] <format> <spans...>");
    puts("       fast-completer --generate-blob <schema> [output]");
    puts("       fast-completer --check <name>");
    puts("       fast-completer --dump-header <blob>\n");
    puts("       fast-completer --lint <schema>\n");
    puts("Completion mode:");
    puts("  fast-completer [options] <format> <spans...>\n");
    puts("  format        Output format (see below)");
    puts("  spans         Command line tokens starting with CLI name\n");
    puts("  --blob <path>    Use blob at specified path instead of cache lookup");
    puts("  --add-space      Append trailing space to completion values");
    puts("  --full-commands  Complete full leaf command paths instead of next level");
    puts("  --quiet, -q      Silently exit if blob not found (for fallback scripts)");
    puts("                   Unexpected errors (invalid blob, etc.) still print\n");
    puts("  -T, --dynamic-completer-timeout <ms>  Override dynamic completer timeout");
    puts("  Dynamic completers time out after 1000ms by default.");
    puts("  Override with FAST_COMPLETER_TIMEOUT_MS or the flag above (milliseconds).\n");
    puts("  The CLI name is derived from the first span and used to look up");
    puts("  <name>.fcmpb in the cache directory.\n");
    puts("  Cache location (override with FAST_COMPLETER_CACHE env var):");
#ifdef _WIN32
    puts("    %LOCALAPPDATA%\\fast-completer\\<name>.fcmpb");
#else
    puts("    ~/.cache/fast-completer/<name>.fcmpb");
#endif
    puts("");
    puts("Blob generation mode:");
    puts("  fast-completer --generate-blob [options] <schema> [output]\n");
    puts("  schema               Path to schema file");
    puts("  output               Output path (optional - defaults to cache directory)");
    puts("  --big-endian         Generate big-endian blob");
    puts("  --no-descriptions    Omit descriptions entirely (smallest blob)");
    puts("  --short-descriptions First sentence only (default)");
    puts("  --long-descriptions  Include full descriptions");
    puts("  --description-length <n>  Truncate descriptions to n characters\n");
    puts("  Description options can be combined: --long-descriptions --description-length 200");
    puts("  will include full descriptions but truncate any exceeding 200 characters.");
    puts("  If output is omitted, reads 'name' from schema and saves to cache.\n");
    puts("Check mode:");
    puts("  fast-completer --check <name>\n");
    puts("  name              CLI name to check (e.g., 'aws')");
    puts("  Returns exit code 0 if blob exists in cache, 1 otherwise.\n");
    puts("Dump header mode:");
    puts("  fast-completer --dump-header <blob>\n");
    puts("  blob              Path or cache name (e.g., 'aws' or '/path/to/aws.fcmpb')\n");
    puts("Lint mode:");
    puts("  fast-completer --lint <schema>\n");
    puts("  schema            Path to schema file (validate only)\n");
    puts("Output formats:");
    puts("  bash, lines       One value per line (no descriptions)");
    puts("  zsh               value:description");
    puts("  fish, tsv         value\\tdescription");
    puts("  pwsh              PowerShell format");
    puts("  json              JSON array of {\"value\": ..., \"description\": ...}\n");
    puts("Use 'lines' format when descriptions are not needed.\n");
    puts("Examples:");
    puts("  fast-completer --generate-blob aws.fcmps");
    puts("      Generate blob from schema (CLI name derived from first command)\n");
    puts("  fast-completer --check aws && echo 'aws completions available'");
    puts("      Conditionally run command if aws blob exists\n");
    puts("  fast-completer -q json aws s3 \"\" || fallback_completer aws s3");
    puts("      Try completions, fall back if blob not found\n");
    puts("  fast-completer -T 500 bash aws s3 \"\"");
    puts("      Use a 500ms dynamic completer timeout\n");
    puts("  fast-completer bash aws s3 \"\"");
    puts("      Complete subcommands after 'aws s3'\n");
    puts("  fast-completer --blob /path/to/custom.fcmpb zsh mycli --");
    puts("      Complete flags using explicit blob path\n");
    puts("  fast-completer --dump-header aws");
    puts("      Dump header of cached aws.fcmpb blob");
}

// Execution modes (mutually exclusive)
typedef enum {
    MODE_COMPLETE,       // Default: generate completions
    MODE_CHECK,          // --check: test if blob exists
    MODE_DUMP_HEADER,    // --dump-header: show blob header
    MODE_GENERATE_BLOB,  // --generate-blob: create blob from schema
    MODE_LINT            // --lint: validate schema
} Mode;

int main(int argc, char *argv[]) {
    // Mode selection
    Mode mode = MODE_COMPLETE;

    // Completion mode options
    const char *explicit_blob_path = NULL;
    bool complete_opts_used = false;  // Track if completion-specific options were used

    // Generate-blob mode options
    bool big_endian = false;
    DescriptionMode desc_mode = DESC_SHORT;
    size_t desc_max_len = 0;
    bool generate_opts_used = false;  // Track if generate-blob-specific options were used

    // Long options table
    static struct option long_options[] = {
        // Universal
        {"help",               no_argument,       0, 'h'},

        // Mode selectors (mutually exclusive)
        {"check",              no_argument,       0, 'C'},
        {"dump-header",        no_argument,       0, 'D'},
        {"generate-blob",      no_argument,       0, 'G'},
        {"lint",               no_argument,       0, 'I'},

        // Completion mode options
        {"blob",               required_argument, 0, 'b'},
        {"add-space",          no_argument,       0, 'a'},
        {"full-commands",      no_argument,       0, 'f'},
        {"quiet",              no_argument,       0, 'q'},
        {"dynamic-completer-timeout", required_argument, 0, 'T'},

        // Generate-blob mode options
        {"big-endian",         no_argument,       0, 'E'},
        {"no-descriptions",    no_argument,       0, 'N'},
        {"short-descriptions", no_argument,       0, 'S'},
        {"long-descriptions",  no_argument,       0, 'L'},
        {"description-length", required_argument, 0, 'l'},

        {0, 0, 0, 0}
    };

    // '+' = POSIX mode (stop at first non-option = the format arg)
    int c;
    while ((c = getopt_long(argc, argv, "+hqafIb:l:T:", long_options, NULL)) != -1) {
        switch (c) {
            // Universal
            case 'h':
                print_help();
                return 0;

            // Mode selectors (mutually exclusive)
            case 'C':  // --check
                if (mode != MODE_COMPLETE) {
                    fprintf(stderr, "Error: --check, --dump-header, --generate-blob, and --lint are mutually exclusive\n");
                    return 1;
                }
                mode = MODE_CHECK;
                break;
            case 'D':  // --dump-header
                if (mode != MODE_COMPLETE) {
                    fprintf(stderr, "Error: --check, --dump-header, --generate-blob, and --lint are mutually exclusive\n");
                    return 1;
                }
                mode = MODE_DUMP_HEADER;
                break;
            case 'G':  // --generate-blob
                if (mode != MODE_COMPLETE) {
                    fprintf(stderr, "Error: --check, --dump-header, --generate-blob, and --lint are mutually exclusive\n");
                    return 1;
                }
                mode = MODE_GENERATE_BLOB;
                break;
            case 'I':  // --lint
                if (mode != MODE_COMPLETE) {
                    fprintf(stderr, "Error: --check, --dump-header, --generate-blob, and --lint are mutually exclusive\n");
                    return 1;
                }
                mode = MODE_LINT;
                break;

            // Completion mode options
            case 'b':  // --blob
                explicit_blob_path = optarg;
                complete_opts_used = true;
                break;
            case 'a':  // --add-space
                add_trailing_space = true;
                complete_opts_used = true;
                break;
            case 'f':  // --full-commands
                full_commands = true;
                complete_opts_used = true;
                break;
            case 'q':  // --quiet, -q
                quiet_mode = true;
                complete_opts_used = true;
                break;
            case 'T':  // --dynamic-completer-timeout
                {
                    char *endptr = NULL;
                    long val = strtol(optarg, &endptr, 10);
                    if (!endptr || *endptr != '\0' || val <= 0) {
                        fprintf(stderr, "--dynamic-completer-timeout must be a positive integer (milliseconds)\n");
                        return 1;
                    }
                    if (val > INT32_MAX) val = INT32_MAX;
                    g_completer_timeout_ms = (int)val;
                    g_completer_timeout_override = true;
                    complete_opts_used = true;
                }
                break;

            // Generate-blob mode options
            case 'E':  // --big-endian
                big_endian = true;
                generate_opts_used = true;
                break;
            case 'N':  // --no-descriptions
                desc_mode = DESC_NONE;
                generate_opts_used = true;
                break;
            case 'S':  // --short-descriptions
                desc_mode = DESC_SHORT;
                generate_opts_used = true;
                break;
            case 'L':  // --long-descriptions
                desc_mode = DESC_LONG;
                generate_opts_used = true;
                break;
            case 'l':  // --description-length
                {
                    char *endptr;
                    unsigned long val = strtoul(optarg, &endptr, 10);
                    if (*endptr != '\0' || val < 4) {
                        fprintf(stderr, "--description-length must be an integer >= 4\n");
                        return 1;
                    }
                    desc_max_len = (size_t)val;
                    generate_opts_used = true;
                }
                break;

            case '?':
                // getopt_long already printed an error message
                fprintf(stderr, "Try 'fast-completer --help' for more information.\n");
                return 1;

            default:
                fprintf(stderr, "Unexpected option: %c\n", c);
                return 1;
        }
    }

    // Validate option/mode compatibility
    if (generate_opts_used && mode != MODE_GENERATE_BLOB) {
        fprintf(stderr, "Error: --big-endian, --no-descriptions, --short-descriptions, --long-descriptions, and --description-length are only valid with --generate-blob\n");
        return 1;
    }
    if (complete_opts_used && mode != MODE_COMPLETE) {
        fprintf(stderr, "Error: --blob, --add-space, --full-commands, --quiet, and --dynamic-completer-timeout are only valid in completion mode\n");
        return 1;
    }

    // Dispatch based on mode
    switch (mode) {
        case MODE_CHECK: {
            if (argc != optind + 1) {
                fprintf(stderr, "Usage: fast-completer --check <name>\n");
                return 1;
            }
            char *path = resolve_blob_path(argv[optind]);
            if (!path) return 1;
#ifdef _WIN32
            DWORD attrs = GetFileAttributesA(path);
            return (attrs != INVALID_FILE_ATTRIBUTES) ? 0 : 1;
#else
            struct stat st;
            return (stat(path, &st) == 0) ? 0 : 1;
#endif
        }

        case MODE_DUMP_HEADER: {
            if (argc != optind + 1) {
                fprintf(stderr, "Usage: fast-completer --dump-header <blob>\n");
                return 1;
            }
            char *path = resolve_blob_path(argv[optind]);
            if (!load_blob(path)) {
                return 1;
            }
            dump_header(path);
            return 0;
        }

        case MODE_GENERATE_BLOB: {
            if (argc < optind + 1 || argc > optind + 2) {
                fprintf(stderr, "Usage: fast-completer --generate-blob [options] <schema> [output]\n");
                fprintf(stderr, "Options: --big-endian, --no-descriptions, --short-descriptions, --long-descriptions, --description-length <n>\n");
                return 1;
            }

            const char *schema_path = argv[optind];
            const char *output_path = (argc == optind + 2) ? argv[optind + 1] : NULL;
            char *derived_path = NULL;

            // If no output path, derive from schema's "name" property
            if (!output_path) {
                char *name = get_schema_name(schema_path);
                if (!name) {
                    fprintf(stderr, "Schema must have 'name' property when output path is omitted\n");
                    return 1;
                }
                ensure_cache_dir();
                derived_path = build_cache_path(name);
                output_path = derived_path;
            }

            bool result = generate_blob(schema_path, output_path, big_endian, desc_mode, desc_max_len);
            return result ? 0 : 1;
        }

        case MODE_LINT: {
            if (argc != optind + 1) {
                fprintf(stderr, "Usage: fast-completer --lint <schema>\n");
                return 1;
            }
            bool ok = lint_schema(argv[optind]);
            return ok ? 0 : 1;
        }

        case MODE_COMPLETE:
            break;  // Fall through to completion logic below
    }

    // Completion mode
    if (argc < optind + 2) {
        fprintf(stderr, "Usage: fast-completer [options] <format> <spans...>\n");
        fprintf(stderr, "Try 'fast-completer --help' for more information.\n");
        return 1;
    }

    init_completer_timeout();

    const char *format_name = argv[optind];
    int spans_start = optind + 1;
    const char *cli_name = argv[spans_start];

    // Resolve blob path
    char *resolved_path = NULL;
    const char *blob_path;
    if (explicit_blob_path) {
        blob_path = explicit_blob_path;
    } else {
        resolved_path = resolve_blob_path(cli_name);
        blob_path = resolved_path;
    }

    output_format = parse_format(format_name);
    if (output_format == OUT_UNKNOWN) {
        fprintf(stderr, "Unknown output format: %s\n", format_name);
        fprintf(stderr, "Supported: lines, zsh, tsv, json, pwsh\n");
        return 1;
    }

    // In quiet mode, check if blob exists before attempting load (avoids error output)
    if (quiet_mode) {
#ifdef _WIN32
        if (GetFileAttributesA(blob_path) == INVALID_FILE_ATTRIBUTES)
            return 1;
#else
        if (access(blob_path, F_OK) != 0)
            return 1;
#endif
    }

    if (!load_blob(blob_path)) {
        // If cache lookup failed, show helpful error (unless --quiet)
        if (!quiet_mode && !explicit_blob_path && is_simple_name(cli_name)) {
            char *cache_dir = get_cache_dir();
            fprintf(stderr, "Blob '%s' not found in %s\n", cli_name, cache_dir ? cache_dir : "(unknown)");
            fprintf(stderr, "Generate it with: fast-completer --generate-blob <schema>\n");
        }
        return 1;
    }

    // Allocate path buffer only when needed for --full-commands
    if (full_commands) {
        path_buf = malloc(header.max_command_path_len);
        if (!path_buf) {
            perror("malloc");
            return 1;
        }
    }

    flockfile(stdout);
    complete(argc - spans_start, (const char **)(argv + spans_start));
    funlockfile(stdout);

    completer_cache_clear();

    return 0;
}
